### ISSUE TITLE
Redis Replication 적용 및 Sentinel로 자동 장애 조치

### ISSUE THREAD

**Issue by kyungjinleelee** [pickple-ecommerce/backend#118]
## TODO
- [x]  master-replica(slave) 구조 구축
- [x]  sentinel 구조 구축
- [x]  read/insert 테스트 (로컬 cmd cli)
