### ISSUE TITLE
프로젝트 멀티 모듈 전환

### ISSUE THREAD

**Issue by kimjinmyeong** [pickple-ecommerce/backend#23]
## TODO

- [ ]  backend 디렉토리를 Gradle 모듈화
- [ ]  각 서비스 별 build.gradle 설정 
- [ ]  build 시 jar 파일 생성 예외 설정
