### ISSUE TITLE
Payment 서비스에 errorEvent 추가

### ISSUE THREAD

**Issue by MeGuuuun** [pickple-ecommerce/backend#41]
## TODO

- [x]  errorEvent 논의해서 양식 정하기 → 각 토픽 별로 error 추가하기로
- [x] Kafka 메세지 양식 수정 사항 반영
- [x]  Payment에 errorEvent 추가하기
    - [x]  메세지 검증 과정 추가하기
