### ISSUE TITLE
상품, 재고 서비스 기본 설계

### ISSUE THREAD

**Issue by kyungjinleelee** [pickple-ecommerce/backend#50]
## TODO
- [x]  예외 커스텀 클래스 생성
- [x]  상품 엔티티 파일 작성
- [x]  재고 엔티티 파일 생성
- [ ]  재고 감소 메서드 설계
- [x]  일반 상품, 예약구매 상품 엔티티 분리
- [x]  기본 컨트롤러, 서비스, 레포 파일 작성
