### ISSUE TITLE
Payment Controller 구현 및 Audit Aware 추가

### ISSUE THREAD

**Issue by MeGuuuun** [pickple-ecommerce/backend#52]
## TODO

- [x] Audit Aware 추가
    - [x] 논리적 삭제 구현 
- [x]  Payment Controller API 구현
    - [x] 결제 단건 조회
    - [x] 결제 전체 조회
    - [x] 결제 삭제
