### ISSUE TITLE
Notification Grafana 연동 후 슬랙 알림 기능 구현

### ISSUE THREAD

**Issue by MeGuuuun** [pickple-ecommerce/backend#54]
## TODO

- [x] Grafana 연동 후 슬랙으로 알림 보내는 기능 테스트
- [ ] 기본 API 구현
    - [ ] 알림 생성
    - [ ] 알림 삭제
    - [ ] 알림 조회(admin)

채널별 알림 설정
- [ ] slack → 관리자 알림
- [ ] email → user 알림

고려사항
- [ ] 알림의 type(주문, 결제, 배송 등)을 enum으로 common-module에 넣어 사용 할 지... 논의해보기
