### ISSUE TITLE
Apache Cassandra에서 MongoDB로 마이그레이션

### ISSUE THREAD

**Issue by kimjinmyeong** [pickple-ecommerce/backend#57]
## TODO

- [ ] MongoDB 도커 컴포즈 작성
- [ ] Spring과 MongoDB 연결
- [ ] 기존 엔티티 코드 수정
