### ISSUE TITLE
Payment ExceptionHandler 추가 및 db-init 수정

### ISSUE THREAD

**Issue by MeGuuuun** [pickple-ecommerce/backend#61]
## TODO

- [ ] ExceptionHandler 추가
- [ ] db-init sql 파일 수정
- [ ] jpaAuditingHandler Bean 관련 에러 떠서 해결
- [ ] 이 외 자잘한 부분들 수정..
