### ISSUE TITLE
docker-compose 오류 수정

### ISSUE THREAD

**Issue by MeGuuuun** [pickple-ecommerce/backend#66]
## TODO

docker-compose 파일 내 도커 볼륨 사항 수정

- [ ]  .github 폴더 하위에 위치한 prometheus 폴더 삭제
- [ ]  prometheus와 grafana 도커 볼륨 수정
    - [ ]  prometheus/config 에 prometheus.yml 추가
    - [ ]  grafana/provisioning/dashboards 에 gf_dashboard.json 추가
    - [ ]  grafana/provisioning/datasources 에 gf_datasource.yml 추가
- [ ] 도커 볼륨과 마운트 된 로컬 폴더 git ignore 지정
