### ISSUE TITLE
api gateway, auth 서비스 설정

### ISSUE THREAD

**Issue by kyungjinleelee** [pickple-ecommerce/backend#7]
## TODO
- [x]  spring security 관련 설정
- [x]  GlobalFilter 및 각종 filter 설정
- [x]  User 정보 FeignClient 구현
    - [x]  DTO 작성
- [x] jwt 설정
- [x] [Auth] 회원가입 구현
- [x] [Auth] 로그인 구현
