### ISSUE TITLE
Notification SMTP 이메일 알림 기능 구현

### ISSUE THREAD

**Issue by MeGuuuun** [pickple-ecommerce/backend#74]
## TODO

- [x] MimeMessage 사용해 구글 이메일 주소로 이메일 보내기
- [x] init-notification.sql에 notification_id 초기화 값 생성
- [ ] 알림 CRUD
    - [x] 알림 생성
    - [x] 알림 저장
    - [x] 알림 삭제
    - [x] 알림 조회 
    - [x] 알림 채널 추가
    - [x] 알림 채널 삭제
