### ISSUE TITLE
Payment 기본 CRUD 구현 및 PostgreSQL 연동

### ISSUE THREAD

**Issue by MeGuuuun** [pickple-ecommerce/backend#8]
## TODO

- [x]  DDD 구조에 맞춰 디렉토리 분리
- [x]  기본 클래스 구현
    - [x] 결제 생성
    - [x] 결제 조회
    - [x] 결제 삭제
- [x]  PostgreSQL 연동
- [x] Kafka 연동
- [x] Payment 엔티티 approvalNumber 삭제
