### ISSUE TITLE
각 서비스 도커화

### ISSUE THREAD

**Issue by kimjinmyeong** [pickple-ecommerce/backend#84]
## TODO

- [ ] 민감 정보 환경 변수로 정의
- [ ] 배포 인스턴스 분리에 따른 docker compose 분리
- [ ] 스프링 서비스들 dockerfile 작성
